name: Send webmentions for new blog posts
on:
  rss:
    url: https://robbinespu.gitlab.io/indieweb/index.xml
    config:
      logLevel: debug
      limit: 10
jobs:
  send_webmentions:
    name: Send webmentions
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "auto publish via bridgy"
        uses: wei/curl@v1
        with:
         args: -i -d source=${{on.rss.outputs.link}} -d target=https://brid.gy/publish/twitter https://brid.gy/publish/webmention
         is_debug: true
            
