name: auto publish to twitter for new indieweb posts
on:
  rss:
    url: https://robbinespu.gitlab.io/indieweb/index.xml
    config:
      logLevel: debug
      limit: 10
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
         args: -i -d source=${{on.rss.outputs.link}} -d target=https://brid.gy/publish/twitter https://brid.gy/publish/webmention
         is_debug: true
            
