name: Send webmentions for new blog posts
on:
  rss:
    url: https://robbinespu.gitlab.io/indieweb/index.xml
    config:
      logLevel: debug
      limit: 10
jobs:
  send_webmentions:
    name: Send webmentions
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    
      - name: "Send webmentions for RSS item link"
        uses: actionsflow/axios@v1
        with:
          url: https://webmention.app/check/
          method: "POST"
          params: '{ "url": "${{on.rss.outputs.link}}", "token": "${{ secrets.WM_TOKEN }}" }'
          is_debug: true
          
      - name: "Bridgy twitter"
        run: |
          curl -i \
          -d source=https://robbinespu.gitlab.io/indieweb/211015034814/ \
          -d target=https://brid.gy/publish/twitter \
          https://brid.gy/publish/webmention
