name: Send webmentions for new blog posts
on:
  rss:
    url: https://journal.robbi.my/index.xml
    config:
      logLevel: debug
      limit: 1
jobs:
  send_webmentions:
    name: Send webmentions
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    
      # - name: "Send webmentions for RSS item link"
      #   uses: actionsflow/axios@v1
      #   with:
      #     url: https://www.webmention.app/check/
      #     method: "POST"
      #     params: '{ "url": "${{on.rss.outputs.link}}", "token": "${{ secrets.WM_TOKEN }}" }'
      #     is_debug: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install webmention-cli
        run: npm install -g webmention

      - name: Send webmentions
        run: npx webmention "${{on.rss.outputs.link}}" --send --debug
 
