name: Send Webmentions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  send-webmentions:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm install xml2js # Install xml2js library
        npm install webmention
        npm install node-fetch
      # or use 'yarn add xml2js' if you use Yarn

    - name: Send Webmentions
      run: node send-webmentions.js # Replace with your script

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Send webmentions"
        git push
